# Generated by Django 5.1.4 on 2024-12-22 00:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='post',
            old_name='conent',
            new_name='content',
        ),
    ]
